name: portal_karyawan
description: Proof of concept portal karyawan (berita, event, survey, cuti, slip gaji).
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^22.3.1
  http: ^1.6.0
  ota_update: ^7.1.0
  package_info_plus: ^10.2.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
